//
//  DetailProtocols.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import Foundation

//MARK: Wireframe -
protocol DetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailPresenterProtocol: class {

    var interactor: DetailInteractorInputProtocol? { get set }
    var view: DetailViewProtocol? {get set}
    var wireFrame: DetailWireframeProtocol? {get set}

}

//MARK: Interactor -
protocol DetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DetailInteractorInputProtocol: class {

    var presenter: DetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DetailViewProtocol: class {

    var presenter: DetailPresenterProtocol?  { get set }
    var favoriteShow: FavoriteShows?  { get set }
    /* Presenter -> ViewController */
    
    
    
}





