//
//  TableProtocols.swift
//  BancaDigital
//
//  Created Jorge Parra on 21/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import UIKit

//MARK: Wireframe -
protocol TableWireframeProtocol: class {
    func callDetail(with : FavoriteShows)
    var viewController: UIViewController? {get set}
}
//MARK: Presenter -
protocol TablePresenterProtocol: class {

    var interactor: TableInteractorInputProtocol? { get set }
    var view: TableViewProtocol? {get set}
    var wireFrame: TableWireframeProtocol? {get set}
    var listImageTextAndImageModel : [ImageTextAndImageModel]? {get set}
    var adapter : ApiAdapterCallImageTextAndImageModel? {get set}
    
    /* Presenter */
    func callAPI(with : Int)
    func saveCoredata(with : Int)
    func deleteCoredata(with : Int)
    func callDetail(with : Int)
    

}

//MARK: Interactor -
protocol TableInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func didDelete(with : Int)
}

protocol TableInteractorInputProtocol: class {

    var presenter: TableInteractorOutputProtocol?  { get set }
    /* Presenter -> Interactor */
    func callAPI(with call : Int, callback: @escaping (ServerResponse) -> Void)
    func saveCoredata(_ :APIShowsResponseElement)
    func deleteCoredata(with : Int)
}

//MARK: View -
protocol TableViewProtocol: class {
    var tabTitle: (title:String, typeOfCall: Int)?  { get set }
    
    var presenter: TablePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func apiResponse(with :[ImageTextAndImageModel] )
    func callErrorMessage()
    func didDelete(answer:Int)
    
}



