//
//  DetailViewController.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import UIKit

class DetailViewController: UIViewController, DetailViewProtocol {
    var favoriteShow: FavoriteShows?
    @IBOutlet weak var label: UILabel!
    @IBOutlet weak var imdbButton: UIBarButtonItem!
    
    @IBOutlet weak var showImage: UIImageView!
    
	var presenter: DetailPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
       
        guard let show = favoriteShow else {fatalError()}
        do{
            try showImage.imageFromUrl(url:   URL(string: (favoriteShow?.image)!)!)
        }catch{
            print("error")
        }
        
        label.attributedText = NSAttributedString().stringFromHtml(string: show.summary ?? "")
   
            
        self.title = show.name
        
        if show.externals == nil {
            imdbButton.isEnabled = false
            imdbButton.tintColor = .clear
        }
        
    }
    
    @IBAction func imdbClicked(_ sender: Any) {
        
        
        guard let url = favoriteShow!.externals else {fatalError()}
        showDetailViewController(WebviewWireframe.createModule(with: url), sender: self)
        
    }
    


}
