//
//  TableInteractor.swift
//  BancaDigital
//
//  Created Jorge Parra on 21/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//
import Foundation
import UIKit
import CoreData



class TableInteractor: TableInteractorInputProtocol {
    func deleteCoredata(with id : Int) {
        CoreDataManager.shared.deleteFavoriteShows(withId: id )
        presenter?.didDelete(with: id)
    }
    
    
    weak var presenter: TableInteractorOutputProtocol?
    
    func callAPI(with call: Int,callback: @escaping (ServerResponse) -> Void) {
        
        let calltype = typeOfCall(rawValue: call)
        
        if (calltype == .server) {
            NetworkManager.shared.get{ response in
                switch response {
                case .error :
                    callback(.error)
                case .succesfull(let responseShows) :
                    callback(.succesfull(list: responseShows))
                
                default:
                    break
                }
            
            }
        }else  {
            do{
                callback(.core(list: try CoreDataManager.shared.fetchFavoriteShows()))
            }catch{
                callback(.error)
            }
        }
}
    
    
    func saveCoredata(_ element: APIShowsResponseElement) {
        CoreDataManager.shared.saveFavoriteShows(show: element)
    }
    
//    func deleteCoredata(with show: FavoriteShows) {
//
//
//
//    }
    
    
}

