//
//  WebviewViewController.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import UIKit
import WebKit

class WebviewViewController: UIViewController, WebviewViewProtocol {

    @IBOutlet weak var webview: WKWebView!
    var presenter: WebviewPresenterProtocol?
    var urltV : String?
	override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.navigationBar.isHidden =  true
        if let urlRequest = URL(string:"https://www.imdb.com/title/" + urltV! + "/" ) {
            webview.load(URLRequest(url: urlRequest))
        }
       
    }

}



