//
//  WebviewPresenter.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres
//

import UIKit

class WebviewPresenter: WebviewPresenterProtocol, WebviewInteractorOutputProtocol {

    var view: WebviewViewProtocol?
    var interactor: WebviewInteractorInputProtocol?
    var wireFrame: WebviewWireframeProtocol?

    

}
