//
//  WebviewRouter.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres
//

import UIKit

class WebviewWireframe: WebviewWireframeProtocol {

    weak var viewController: UIViewController?


    //If you dont want to pass data from a VIPER-X Module to another remove tha param data_to_pass from the function
    static func createModule(with data_to_pass:String) -> UIViewController {
        let navController = Webviewstoryboard.instantiateViewController(withIdentifier: "nav_web")
        if let view = navController.children.first as? WebviewViewProtocol {

        let interactor : WebviewInteractorInputProtocol     =  WebviewInteractor()
        let router : WebviewWireframeProtocol =  WebviewWireframe()
       
        let presenter: WebviewPresenterProtocol & WebviewInteractorOutputProtocol = WebviewPresenter()

            view.urltV = data_to_pass
            view.presenter = presenter
            presenter.view = view
            presenter.wireFrame = router
            presenter.interactor = interactor
            interactor.presenter = presenter
            
		     return navController

}
            return UIViewController()

    }


   static var Webviewstoryboard: UIStoryboard {
        return UIStoryboard(name: "Webview", bundle: Bundle.main)
    }




}
