//
//  WebviewProtocols.swift
//  BancaDigital
//
//  Created Jorge Parra on 22/08/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Carlos Torres, Inspired by Juanpe Catalán VIPER Template
//

import Foundation

//MARK: Wireframe -
protocol WebviewWireframeProtocol: class {

}
//MARK: Presenter -
protocol WebviewPresenterProtocol: class {

    var interactor: WebviewInteractorInputProtocol? { get set }
    var view: WebviewViewProtocol? {get set}
    var wireFrame: WebviewWireframeProtocol? {get set}
  
    

}

//MARK: Interactor -
protocol WebviewInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol WebviewInteractorInputProtocol: class {

    var presenter: WebviewInteractorOutputProtocol?  { get set }
    /* Presenter -> Interactor */
}

//MARK: View -
protocol WebviewViewProtocol: class {

    var presenter: WebviewPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    var urltV: String? {get set}
}



